name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Rust
#      run: rustup update stable
#    - name: Install wasm-pack
#      run: cargo install wasm-pack
#    - name: Install trunk
#      run: cargo install trunk
#    - name: Build with trunk
#      run: trunk build --release
#    - name: Deploy to GitHub Pages
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: ./dist
#
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutzzz
        uses: actions/checkout@v3
      #      - name: Restore cache
      #        uses: actions/cache@v3
      #        with:
      #          path: |
      #            ~/.cargo/bin
      #            ~/.cargo/git
      #            ~/.cargo/registry
      #            target
      #          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: "latest"
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build the Rust WASM app and all of its assets
        run: trunk build --public-url ${{ github.event.repository.name }} --release

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    

    permissions:
      pages: write

      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v
